//! `anyrt drift` — the API-drift detector (plan §4 drift flow). The
//! any client is curated, never autogenerated; drift is event-driven:
//! a vendored OpenAPI 3.1 pin (`/v1/openapi.json`) + a coverage
//! manifest (endpoint → mapping | excluded), each endpoint carrying a
//! fingerprint of its CONTRACT.
//! Fingerprints hash the RESOLVED shapes — params, body and response
//! schemas with every `$ref` expanded transitively (cycle-guarded) and
//! prose stripped — so a field added to a referenced definition is
//! drift, while description churn is not. `make api-drift` exits
//! nonzero on new / removed / changed endpoints; `anyrt drift
//! --refresh` rewrites the fingerprints of already-triaged endpoints
//! (new/removed stay human-triaged — refresh never adds or drops
//! manifest entries).

use serde_json::{json, Map, Value};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::Path;

const METHODS: [&str; 5] = ["get", "post", "put", "delete", "patch"];
// prose-only keys, ignored at every nesting level
const PROSE: [&str; 4] = ["description", "example", "examples", "title"];

fn canonical(v: &Value) -> String {
    serde_json::to_string(v).expect("json serializes")
}

/// Follow a local `#/…` JSON pointer into the spec.
fn deref<'a>(spec: &'a Value, r: &str) -> Option<&'a Value> {
    let mut cur = spec;
    for seg in r.strip_prefix("#/")?.split('/') {
        cur = cur.get(seg)?;
    }
    Some(cur)
}

/// Deep-copy a schema with `$ref`s expanded and prose dropped. A ref
/// already on the resolution stack (a cycle) stays as its name — the
/// name then stands for the shape, which is stable and terminating.
fn resolve(schema: &Value, spec: &Value, stack: &mut Vec<String>) -> Value {
    if let Some(r) = schema.get("$ref").and_then(|r| r.as_str()) {
        if stack.iter().any(|s| s == r) {
            return json!(r);
        }
        let Some(def) = deref(spec, r) else {
            return json!(r); // dangling ref — keep the name
        };
        stack.push(r.to_string());
        let out = resolve(def, spec, stack);
        stack.pop();
        return out;
    }
    match schema {
        Value::Object(map) => Value::Object(
            map.iter()
                .filter(|(k, _)| !PROSE.contains(&k.as_str()))
                .map(|(k, v)| (k.clone(), resolve(v, spec, stack)))
                .collect(),
        ),
        Value::Array(items) => {
            Value::Array(items.iter().map(|v| resolve(v, spec, stack)).collect())
        }
        _ => schema.clone(),
    }
}

fn norm_params(params: &[Value], spec: &Value) -> Value {
    let mut out: Vec<Value> = params
        .iter()
        .map(|p| {
            // the whole param, resolved — covers type/format/enum/items
            let mut o = resolve(p, spec, &mut Vec::new());
            o["required"] = json!(o.get("required").and_then(|r| r.as_bool()).unwrap_or(false));
            o
        })
        .collect();
    out.sort_by_key(|x| {
        (
            x["in"].as_str().unwrap_or("").to_string(),
            x["name"].as_str().unwrap_or("").to_string(),
        )
    });
    Value::Array(out)
}

fn norm_body(request_body: &Value, spec: &Value) -> Value {
    // openapi 3.x: requestBody.content[<media>].schema — reduce to the
    // RESOLVED schema shape
    if let Some(content) = request_body.get("content").and_then(|c| c.as_object()) {
        if let Some((_, media)) = content.iter().next() {
            return resolve(&media["schema"], spec, &mut Vec::new());
        }
    }
    Value::Null
}

fn norm_responses(op: &Value, spec: &Value) -> Value {
    let mut out = Map::new();
    if let Some(responses) = op["responses"].as_object() {
        for (status, resp) in responses {
            out.insert(status.clone(), resolve(resp, spec, &mut Vec::new()));
        }
    }
    Value::Object(out) // Map is a BTreeMap — sorted on serialize
}

pub fn endpoint_fingerprint(op: &Value, spec: &Value) -> String {
    let empty = Vec::new();
    let params = op["parameters"].as_array().unwrap_or(&empty);
    let material = json!({
        "parameters": norm_params(params, spec),
        "requestBody": norm_body(&op["requestBody"], spec),
        "responses": norm_responses(op, spec),
    });
    let digest = Sha256::digest(canonical(&material).as_bytes());
    format!("sha256:{}", &hex::encode(digest)[..16])
}

/// {"METHOD /path": fingerprint} for every operation in the spec.
pub fn extract_endpoints(spec: &Value) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    if let Some(paths) = spec["paths"].as_object() {
        for (path, ops) in paths {
            if let Some(ops) = ops.as_object() {
                for (method, op) in ops {
                    if METHODS.contains(&method.as_str()) {
                        out.insert(
                            format!("{} {path}", method.to_uppercase()),
                            endpoint_fingerprint(op, spec),
                        );
                    }
                }
            }
        }
    }
    out
}

#[derive(Default)]
pub struct Drift {
    pub new: Vec<String>,
    pub removed: Vec<String>,
    pub changed: Vec<String>,
}

impl Drift {
    pub fn clean(&self) -> bool {
        self.new.is_empty() && self.removed.is_empty() && self.changed.is_empty()
    }
}

pub fn diff(spec_endpoints: &BTreeMap<String, String>, manifest: &Value) -> Drift {
    let empty = Map::new();
    let covered = manifest["endpoints"].as_object().unwrap_or(&empty);
    let mut d = Drift::default();
    for (ep, fp) in spec_endpoints {
        match covered.get(ep) {
            None => d.new.push(ep.clone()),
            Some(entry) if entry["fingerprint"] != *fp => d.changed.push(ep.clone()),
            _ => {}
        }
    }
    for ep in covered.keys() {
        if !spec_endpoints.contains_key(ep) {
            d.removed.push(ep.clone());
        }
    }
    d.removed.sort();
    d
}

pub fn render(d: &Drift) -> String {
    if d.clean() {
        return "api-drift: clean — manifest matches the vendored spec.".into();
    }
    let mut lines = vec!["api-drift: DRIFT DETECTED".to_string()];
    for (label, items) in [
        ("new (uncovered)", &d.new),
        ("removed (stale mapping)", &d.removed),
        ("changed (contract drift)", &d.changed),
    ] {
        if !items.is_empty() {
            lines.push(format!("\n  {label}:"));
            lines.extend(items.iter().map(|ep| format!("    {ep}")));
        }
    }
    lines.join("\n")
}

fn load(spec_path: &Path, manifest_path: &Path) -> anyhow::Result<(Value, Value)> {
    let spec: Value = serde_json::from_str(&std::fs::read_to_string(spec_path)?)?;
    let manifest: Value = if manifest_path.exists() {
        serde_json::from_str(&std::fs::read_to_string(manifest_path)?)?
    } else {
        json!({"endpoints": {}})
    };
    Ok((spec, manifest))
}

pub fn run(spec_path: &Path, manifest_path: &Path) -> anyhow::Result<bool> {
    let (spec, manifest) = load(spec_path, manifest_path)?;
    let d = diff(&extract_endpoints(&spec), &manifest);
    println!("{}", render(&d));
    Ok(d.clean())
}

/// Rewrite the fingerprints of endpoints present in BOTH spec and
/// manifest (mapping/excluded untouched); report new/removed for human
/// triage. Returns clean = nothing left untriaged.
pub fn refresh(spec_path: &Path, manifest_path: &Path) -> anyhow::Result<bool> {
    let (spec, mut manifest) = load(spec_path, manifest_path)?;
    let spec_endpoints = extract_endpoints(&spec);
    let mut refreshed = Vec::new();
    if let Some(covered) = manifest["endpoints"].as_object_mut() {
        for (ep, entry) in covered.iter_mut() {
            if let Some(fp) = spec_endpoints.get(ep) {
                if entry["fingerprint"] != *fp {
                    entry["fingerprint"] = json!(fp);
                    refreshed.push(ep.clone());
                }
            }
        }
    }
    std::fs::write(
        manifest_path,
        serde_json::to_string_pretty(&manifest)? + "\n",
    )?;
    let d = diff(&spec_endpoints, &manifest);
    println!(
        "api-drift: refreshed {} fingerprint(s){}",
        refreshed.len(),
        if refreshed.is_empty() {
            String::new()
        } else {
            format!(" — {}", refreshed.join(", "))
        }
    );
    if !d.clean() {
        println!("{}", render(&d));
    }
    Ok(d.clean())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fingerprints_match_the_pinned_manifest() {
        // recomputing every fingerprint from the vendored spec proves
        // the manifest was regenerated with THIS algorithm
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap();
        let spec: Value = serde_json::from_str(
            &std::fs::read_to_string(root.join("api/openapi.vendored.json")).unwrap(),
        )
        .unwrap();
        let manifest: Value =
            serde_json::from_str(&std::fs::read_to_string(root.join("api/coverage.json")).unwrap())
                .unwrap();
        let d = diff(&extract_endpoints(&spec), &manifest);
        assert!(d.clean(), "{}", render(&d));
    }

    #[test]
    fn drift_classes() {
        let spec = json!({"paths": {
            "/a": {"get": {"responses": {"200": {}}}},
            "/b": {"post": {"responses": {"200": {}},
                            "parameters": [{"name": "x", "in": "query"}]}},
        }});
        let eps = extract_endpoints(&spec);
        let manifest = json!({"endpoints": {
            "GET /a": {"fingerprint": eps["GET /a"]},
            "POST /b": {"fingerprint": "sha256:wrong"},
            "DELETE /gone": {"fingerprint": "sha256:x"},
        }});
        let d = diff(&eps, &manifest);
        assert!(d.new.is_empty());
        assert_eq!(d.changed, vec!["POST /b"]);
        assert_eq!(d.removed, vec!["DELETE /gone"]);
        assert!(render(&d).contains("contract drift"));
    }

    fn spec_with_field_type(t: &str) -> Value {
        json!({
            "components": {"schemas": {
                "Req": {"type": "object",
                        "properties": {"salience": {"type": t},
                                       "next": {"$ref": "#/components/schemas/Req"}}},
            }},
            "paths": {"/m": {"post": {
                "requestBody": {"content": {"application/json": {
                    "schema": {"$ref": "#/components/schemas/Req"}}}},
                "responses": {"200": {"description": "ok",
                                      "content": {"application/json": {
                                          "schema": {"$ref": "#/components/schemas/Req"}}}}},
            }}},
        })
    }

    #[test]
    fn definition_shape_change_is_drift_and_cycles_terminate() {
        // the 2026-08-01 blind spot: the $ref NAME was hashed, not the
        // shape — salience integer→number went unnoticed. Also: Req is
        // self-referential; resolution must terminate.
        let a = extract_endpoints(&spec_with_field_type("integer"));
        let b = extract_endpoints(&spec_with_field_type("number"));
        assert_ne!(a["POST /m"], b["POST /m"]);
    }

    #[test]
    fn prose_churn_is_not_drift() {
        let mut a = spec_with_field_type("integer");
        let mut b = a.clone();
        a["components"]["schemas"]["Req"]["description"] = json!("old words");
        b["components"]["schemas"]["Req"]["description"] = json!("new words");
        b["paths"]["/m"]["post"]["responses"]["200"]["description"] = json!("fine");
        assert_eq!(
            extract_endpoints(&a)["POST /m"],
            extract_endpoints(&b)["POST /m"]
        );
    }

    #[test]
    fn response_schema_change_is_drift() {
        // status codes alone used to be the whole response material
        let a = spec_with_field_type("integer");
        let mut b = a.clone();
        b["paths"]["/m"]["post"]["responses"]["200"]["content"]["application/json"]["schema"] =
            json!({"type": "string"});
        assert_ne!(
            extract_endpoints(&a)["POST /m"],
            extract_endpoints(&b)["POST /m"]
        );
    }
}
