//! `anyrt drift` — the API-drift detector (plan §4 drift flow). The
//! any client is curated, never autogenerated; drift is event-driven:
//! a vendored swagger pin + a coverage manifest (endpoint → mapping |
//! excluded), each endpoint carrying a fingerprint of its CONTRACT
//! (params/body/response — prose churn is not drift). `make api-drift`
//! exits nonzero on new / removed / changed endpoints.

use serde_json::{json, Map, Value};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::Path;

const METHODS: [&str; 5] = ["get", "post", "put", "delete", "patch"];

fn canonical(v: &Value) -> String {
    serde_json::to_string(v).expect("json serializes")
}

fn norm_params(params: &[Value]) -> Value {
    let mut out: Vec<Value> = params
        .iter()
        .filter(|p| p["in"] != "body") // body handled separately
        .map(|p| {
            let type_ = p
                .get("type")
                .filter(|t| !t.is_null())
                .cloned()
                .or_else(|| p["schema"]["$ref"].as_str().map(|r| json!(r)))
                .unwrap_or(Value::Null);
            json!({"name": p.get("name"), "in": p.get("in"),
                   "required": p.get("required").and_then(|r| r.as_bool())
                       .unwrap_or(false),
                   "type": type_})
        })
        .collect();
    out.sort_by_key(|x| {
        (
            x["in"].as_str().unwrap_or("").to_string(),
            x["name"].as_str().unwrap_or("").to_string(),
        )
    });
    Value::Array(out)
}

fn norm_schema(params: &[Value], request_body: &Value) -> Value {
    // swagger 2.0 puts the body in parameters (in: body); openapi 3 in
    // requestBody — reduce either to the schema $ref/shape
    for p in params {
        if p["in"] == "body" {
            let schema = &p["schema"];
            return schema["$ref"]
                .as_str()
                .map(|r| json!(r))
                .unwrap_or_else(|| schema.clone());
        }
    }
    if let Some(content) = request_body.get("content").and_then(|c| c.as_object()) {
        if let Some((_, media)) = content.iter().next() {
            return media["schema"]["$ref"].clone();
        }
    }
    Value::Null
}

pub fn endpoint_fingerprint(op: &Value) -> String {
    let empty = Vec::new();
    let params = op["parameters"].as_array().unwrap_or(&empty);
    let mut responses: Vec<String> = op["responses"]
        .as_object()
        .map(|o| o.keys().cloned().collect())
        .unwrap_or_default();
    responses.sort();
    let material = json!({
        "parameters": norm_params(params),
        "requestBody": norm_schema(params, &op["requestBody"]),
        "responses": responses,
    });
    let digest = Sha256::digest(canonical(&material).as_bytes());
    format!("sha256:{}", &hex::encode(digest)[..16])
}

/// {"METHOD /path": fingerprint} for every operation in the spec.
pub fn extract_endpoints(spec: &Value) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    if let Some(paths) = spec["paths"].as_object() {
        for (path, ops) in paths {
            if let Some(ops) = ops.as_object() {
                for (method, op) in ops {
                    if METHODS.contains(&method.as_str()) {
                        out.insert(
                            format!("{} {path}", method.to_uppercase()),
                            endpoint_fingerprint(op),
                        );
                    }
                }
            }
        }
    }
    out
}

#[derive(Default)]
pub struct Drift {
    pub new: Vec<String>,
    pub removed: Vec<String>,
    pub changed: Vec<String>,
}

impl Drift {
    pub fn clean(&self) -> bool {
        self.new.is_empty() && self.removed.is_empty() && self.changed.is_empty()
    }
}

pub fn diff(spec_endpoints: &BTreeMap<String, String>, manifest: &Value) -> Drift {
    let empty = Map::new();
    let covered = manifest["endpoints"].as_object().unwrap_or(&empty);
    let mut d = Drift::default();
    for (ep, fp) in spec_endpoints {
        match covered.get(ep) {
            None => d.new.push(ep.clone()),
            Some(entry) if entry["fingerprint"] != *fp => d.changed.push(ep.clone()),
            _ => {}
        }
    }
    for ep in covered.keys() {
        if !spec_endpoints.contains_key(ep) {
            d.removed.push(ep.clone());
        }
    }
    d.removed.sort();
    d
}

pub fn render(d: &Drift) -> String {
    if d.clean() {
        return "api-drift: clean — manifest matches the vendored spec.".into();
    }
    let mut lines = vec!["api-drift: DRIFT DETECTED".to_string()];
    for (label, items) in [
        ("new (uncovered)", &d.new),
        ("removed (stale mapping)", &d.removed),
        ("changed (contract drift)", &d.changed),
    ] {
        if !items.is_empty() {
            lines.push(format!("\n  {label}:"));
            lines.extend(items.iter().map(|ep| format!("    {ep}")));
        }
    }
    lines.join("\n")
}

pub fn run(spec_path: &Path, manifest_path: &Path) -> anyhow::Result<bool> {
    let spec: Value = serde_json::from_str(&std::fs::read_to_string(spec_path)?)?;
    let manifest: Value = if manifest_path.exists() {
        serde_json::from_str(&std::fs::read_to_string(manifest_path)?)?
    } else {
        json!({"endpoints": {}})
    };
    let d = diff(&extract_endpoints(&spec), &manifest);
    println!("{}", render(&d));
    Ok(d.clean())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fingerprints_match_the_pinned_manifest() {
        // the vendored spec + manifest were pinned by the reference
        // implementation — recomputing every fingerprint proves hash
        // parity across the port
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap();
        let spec: Value = serde_json::from_str(
            &std::fs::read_to_string(root.join("api/swagger.vendored.json")).unwrap(),
        )
        .unwrap();
        let manifest: Value =
            serde_json::from_str(&std::fs::read_to_string(root.join("api/coverage.json")).unwrap())
                .unwrap();
        let d = diff(&extract_endpoints(&spec), &manifest);
        assert!(d.clean(), "{}", render(&d));
    }

    #[test]
    fn drift_classes() {
        let spec = json!({"paths": {
            "/a": {"get": {"responses": {"200": {}}}},
            "/b": {"post": {"responses": {"200": {}},
                            "parameters": [{"name": "x", "in": "query"}]}},
        }});
        let eps = extract_endpoints(&spec);
        let manifest = json!({"endpoints": {
            "GET /a": {"fingerprint": eps["GET /a"]},
            "POST /b": {"fingerprint": "sha256:wrong"},
            "DELETE /gone": {"fingerprint": "sha256:x"},
        }});
        let d = diff(&eps, &manifest);
        assert!(d.new.is_empty());
        assert_eq!(d.changed, vec!["POST /b"]);
        assert_eq!(d.removed, vec!["DELETE /gone"]);
        assert!(render(&d).contains("contract drift"));
    }
}
